openapi: 3.1.0
info:
  title: Sample of Bank API
  description: >-
    Sample of Bank API with only one end-point
  version: 1.0.0
servers:
  - url: 'http://localhost:8182'
    description: Local server
paths:
  /age:
    get:
        summary: Validate that person is legal age
        description: >-
            Validate that person is legal age
        operationId: legalAgeValidator
        parameters:
            - name: birthDate
              in: query
              description: >-
                Birth date of person
              required: true
              schema:
                type: string
                format: date
        responses:
            '200':
                description: >-
                    Person is legal age
